### ISSUE TITLE
Roles page getting 500

### ISSUE THREAD

**Issue by balu-lt** [anomalylabs/users-module#11]
Can you take a look at Roles page.
Getting Error 500 on fresh install.

Log:
```
local.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'order clause' (SQL: select `test_users_roles`.* from `test_users_roles` order by `name` asc limit 15 offset 0)' in C:\xampp\htdocs\test\2\vendor\laravel\framework\src\Illuminate\Database\Connection.php:624
```

**Comment by RyanThompson** [comment]
Pull users and reinstall OR

Change title_column to slug in streams_streams DB table for the roles stream in users. Then `run php artisan streams:compile`

That will work for now - pushed a fix as well.. But need to think on this a bit more.
