### ISSUE TITLE
Missing names in roles table

### ISSUE THREAD

**Issue by balu-lt** [anomalylabs/users-module#12]
![role_names](https://cloud.githubusercontent.com/assets/7798162/8835135/3fe093aa-30c1-11e5-84b9-9edf58c30050.png)

**Comment by RyanThompson** [comment]
Hey using streams disto eh!?

I am aware of this one.. I should have it figured out tomorrow I think.

Thanks!

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/multiple-field_type/commit/4c3fbef892c3f670aa98e428d37117d95fd73904
