### ISSUE TITLE
UserWasLoggedIn event not getting fired

### ISSUE THREAD

**Issue by marcogrueter** [anomalylabs/users-module#15]
This is evident as the last_login_at is never updated, and I've tried to listen to it with a different event handler, which never got called.

**Comment by RyanThompson** [comment]
Here's the call: https://github.com/anomalylabs/users-module/blob/1.0/master/src/Authenticator/Authenticator.php#L121

So the listener would listen to `Anomaly\UsersModule\Authenticator\Event\UserWasLoggedIn` or `UserWasLoggedIn::class`

**Comment by RyanThompson** [comment]
Ill double check shortly.
