### ISSUE TITLE
Error when updating Role name (and slug)

### ISSUE THREAD

**Issue by ThinkGraphical** [anomalylabs/users-module#37]
When updating the name of a role (which can result in changing the slug) 
a `HttpException in Application.php line 917` is thrown everywhere in the admin.

Steps to reproduce:
1. Go to roles -> Edit Admin role
2. Change name to SuperAdmin
3. Click 'save and exit'

Also, personally i would change the default name to 'SuperAdmin' instead of 'Admin'.
In the description you already mention "The super admin role." and this allows us to create a 'Admin' role for clients.

**Comment by RyanThompson** [comment]
Hmm.. I feel like maybe slugs should not be editable on edit here since that could break things.
